/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;



/*-------------------------------------------------------------------------------*/




SELECT country,COUNT(customer_id) AS total_customers FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers  DESC


SELECT gender,COUNT(customer_id) AS total_customers FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers  DESC


SELECT category,count(product_id) AS total_products FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC


SELECT AVG(cost) AS average_cost, category FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC



SELECT CASE 
			WHEN category IS NULL THEN 'n/a'
			ELSE category
	   END AS category
,SUM(sales_amount ) AS total_revenue FROM gold.dim_products dp
LEFT JOIN gold.fact_sales fs
ON dp.product_key=fs.product_key
GROUP BY category
HAVING SUM((sales_amount * quantity)) >1
ORDER BY total_revenue DESC






SELECT dc.customer_key,dc.customer_id,dc.first_name,dc.last_name,sum(fs.sales_amount) as Total_revenue FROM gold.dim_customers dc
LEFT JOIN gold.fact_sales fs
ON dc.customer_key=fs.customer_key
GROUP BY dc.customer_key,dc.first_name,dc.last_name,dc.customer_id
ORDER BY Total_revenue DESC





SELECT * FROM gold.dim_customers
SELECT * FROM gold.fact_sales
ORDER BY customer_key





